CREATE TABLE IF NOT EXISTS `persons` (
	`Id` bigint(20) NOT NULL Auto_increment,
	`FirstName` VARCHAR(50) NULL DEFAULT NULL,
	`LastName` VARCHAR(50) NULL DEFAULT NULL,
	`Address` VARCHAR(50) NULL DEFAULT NULL,
	`Gender` VARCHAR(50) NULL DEFAULT NULL,
	`Enabled` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;
